//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Respaldo_Restauracion_Exportar_Excell.Database
{

    [Persistent(@"orderdetails")]
    public partial class Orderdetails : XPLiteObject
    {
        Orders fOrderNumber;
        [Persistent(@"orderNumber")]
        [Association(@"OrderdetailsReferencesOrders")]
        public Orders OrderNumber
        {
            get { return fOrderNumber; }
            set { SetPropertyValue<Orders>(nameof(OrderNumber), ref fOrderNumber, value); }
        }
        Products fProductCode;
        [Size(15)]
        [Persistent(@"productCode")]
        [Association(@"OrderdetailsReferencesProducts")]
        public Products ProductCode
        {
            get { return fProductCode; }
            set { SetPropertyValue<Products>(nameof(ProductCode), ref fProductCode, value); }
        }
        int fQuantityOrdered;
        [Persistent(@"quantityOrdered")]
        public int QuantityOrdered
        {
            get { return fQuantityOrdered; }
            set { SetPropertyValue<int>(nameof(QuantityOrdered), ref fQuantityOrdered, value); }
        }
        decimal fPriceEach;
        [Persistent(@"priceEach")]
        public decimal PriceEach
        {
            get { return fPriceEach; }
            set { SetPropertyValue<decimal>(nameof(PriceEach), ref fPriceEach, value); }
        }
        short fOrderLineNumber;
        [Persistent(@"orderLineNumber")]
        public short OrderLineNumber
        {
            get { return fOrderLineNumber; }
            set { SetPropertyValue<short>(nameof(OrderLineNumber), ref fOrderLineNumber, value); }
        }
        int fId;
        [Key(true)]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
    }

}
