//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Reportes.Database
{

    [Persistent(@"customers")]
    public partial class Customers : XPLiteObject
    {
        int fCustomerNumber;
        [Key]
        [Persistent(@"customerNumber")]
        public int CustomerNumber
        {
            get { return fCustomerNumber; }
            set { SetPropertyValue<int>(nameof(CustomerNumber), ref fCustomerNumber, value); }
        }
        string fCustomerName;
        [Size(50)]
        [Persistent(@"customerName")]
        public string CustomerName
        {
            get { return fCustomerName; }
            set { SetPropertyValue<string>(nameof(CustomerName), ref fCustomerName, value); }
        }
        string fContactLastName;
        [Size(50)]
        [Persistent(@"contactLastName")]
        public string ContactLastName
        {
            get { return fContactLastName; }
            set { SetPropertyValue<string>(nameof(ContactLastName), ref fContactLastName, value); }
        }
        string fContactFirstName;
        [Size(50)]
        [Persistent(@"contactFirstName")]
        public string ContactFirstName
        {
            get { return fContactFirstName; }
            set { SetPropertyValue<string>(nameof(ContactFirstName), ref fContactFirstName, value); }
        }
        string fPhone;
        [Size(50)]
        [Persistent(@"phone")]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fAddressLine1;
        [Size(50)]
        [Persistent(@"addressLine1")]
        public string AddressLine1
        {
            get { return fAddressLine1; }
            set { SetPropertyValue<string>(nameof(AddressLine1), ref fAddressLine1, value); }
        }
        string fAddressLine2;
        [Size(50)]
        [Persistent(@"addressLine2")]
        public string AddressLine2
        {
            get { return fAddressLine2; }
            set { SetPropertyValue<string>(nameof(AddressLine2), ref fAddressLine2, value); }
        }
        string fCity;
        [Size(50)]
        [Persistent(@"city")]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fState;
        [Size(50)]
        [Persistent(@"state")]
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>(nameof(State), ref fState, value); }
        }
        string fPostalCode;
        [Size(15)]
        [Persistent(@"postalCode")]
        public string PostalCode
        {
            get { return fPostalCode; }
            set { SetPropertyValue<string>(nameof(PostalCode), ref fPostalCode, value); }
        }
        string fCountry;
        [Size(50)]
        [Persistent(@"country")]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        Employees fSalesRepEmployeeNumber;
        [Persistent(@"salesRepEmployeeNumber")]
        [Association(@"CustomersReferencesEmployees")]
        public Employees SalesRepEmployeeNumber
        {
            get { return fSalesRepEmployeeNumber; }
            set { SetPropertyValue<Employees>(nameof(SalesRepEmployeeNumber), ref fSalesRepEmployeeNumber, value); }
        }
        decimal fCreditLimit;
        [Persistent(@"creditLimit")]
        public decimal CreditLimit
        {
            get { return fCreditLimit; }
            set { SetPropertyValue<decimal>(nameof(CreditLimit), ref fCreditLimit, value); }
        }
        [Association(@"OrdersReferencesCustomers")]
        public XPCollection<Orders> OrdersCollection { get { return GetCollection<Orders>(nameof(OrdersCollection)); } }
    }

}
