//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Reportes.Database
{

    [Persistent(@"productlines")]
    public partial class Productlines : XPLiteObject
    {
        string fProductLine;
        [Key]
        [Size(50)]
        [Persistent(@"productLine")]
        public string ProductLine
        {
            get { return fProductLine; }
            set { SetPropertyValue<string>(nameof(ProductLine), ref fProductLine, value); }
        }
        string fTextDescription;
        [Size(4000)]
        [Persistent(@"textDescription")]
        public string TextDescription
        {
            get { return fTextDescription; }
            set { SetPropertyValue<string>(nameof(TextDescription), ref fTextDescription, value); }
        }
        string fHtmlDescription;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"htmlDescription")]
        public string HtmlDescription
        {
            get { return fHtmlDescription; }
            set { SetPropertyValue<string>(nameof(HtmlDescription), ref fHtmlDescription, value); }
        }
        byte[] fImage;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"image")]
        [MemberDesignTimeVisibility(true)]
        public byte[] Image
        {
            get { return fImage; }
            set { SetPropertyValue<byte[]>(nameof(Image), ref fImage, value); }
        }
        [Association(@"ProductsReferencesProductlines")]
        public XPCollection<Products> ProductsCollection { get { return GetCollection<Products>(nameof(ProductsCollection)); } }
    }

}
