//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace filtroDevExpress.classicmodels
{

    [Persistent(@"employees")]
    public partial class Employees : XPLiteObject
    {
        int fEmployeeNumber;
        [Key]
        [Persistent(@"employeeNumber")]
        public int EmployeeNumber
        {
            get { return fEmployeeNumber; }
            set { SetPropertyValue<int>(nameof(EmployeeNumber), ref fEmployeeNumber, value); }
        }
        string fLastName;
        [Size(50)]
        [Persistent(@"lastName")]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fFirstName;
        [Size(50)]
        [Persistent(@"firstName")]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fExtension;
        [Size(10)]
        [Persistent(@"extension")]
        public string Extension
        {
            get { return fExtension; }
            set { SetPropertyValue<string>(nameof(Extension), ref fExtension, value); }
        }
        string fEmail;
        [Persistent(@"email")]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        Offices fOfficeCode;
        [Size(10)]
        [Persistent(@"officeCode")]
        [Association(@"EmployeesReferencesOffices")]
        public Offices OfficeCode
        {
            get { return fOfficeCode; }
            set { SetPropertyValue<Offices>(nameof(OfficeCode), ref fOfficeCode, value); }
        }
        Employees fReportsTo;
        [Persistent(@"reportsTo")]
        [Association(@"EmployeesReferencesEmployees")]
        public Employees ReportsTo
        {
            get { return fReportsTo; }
            set { SetPropertyValue<Employees>(nameof(ReportsTo), ref fReportsTo, value); }
        }
        string fJobTitle;
        [Size(50)]
        [Persistent(@"jobTitle")]
        public string JobTitle
        {
            get { return fJobTitle; }
            set { SetPropertyValue<string>(nameof(JobTitle), ref fJobTitle, value); }
        }
        [Association(@"CustomersReferencesEmployees")]
        public XPCollection<Customers> CustomersCollection { get { return GetCollection<Customers>(nameof(CustomersCollection)); } }
        [Association(@"EmployeesReferencesEmployees")]
        public XPCollection<Employees> EmployeesCollection { get { return GetCollection<Employees>(nameof(EmployeesCollection)); } }
    }

}
