//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace filtroDevExpress.classicmodels
{

    [Persistent(@"orderdetails")]
    public partial class Orderdetails : XPLiteObject
    {
        int fQuantityOrdered;
        [Persistent(@"quantityOrdered")]
        public int QuantityOrdered
        {
            get { return fQuantityOrdered; }
            set { SetPropertyValue<int>(nameof(QuantityOrdered), ref fQuantityOrdered, value); }
        }
        decimal fPriceEach;
        [Persistent(@"priceEach")]
        public decimal PriceEach
        {
            get { return fPriceEach; }
            set { SetPropertyValue<decimal>(nameof(PriceEach), ref fPriceEach, value); }
        }
        short fOrderLineNumber;
        [Persistent(@"orderLineNumber")]
        public short OrderLineNumber
        {
            get { return fOrderLineNumber; }
            set { SetPropertyValue<short>(nameof(OrderLineNumber), ref fOrderLineNumber, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("orderNumber")]
            public int OrderNumber { get; set; }
            [Size(15)]
            [Persistent("productCode")]
            public string ProductCode { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
