//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace filtroDevExpress.classicmodels
{

    [Persistent(@"orders")]
    public partial class Orders : XPLiteObject
    {
        int fOrderNumber;
        [Key]
        [Persistent(@"orderNumber")]
        public int OrderNumber
        {
            get { return fOrderNumber; }
            set { SetPropertyValue<int>(nameof(OrderNumber), ref fOrderNumber, value); }
        }
        DateTime fOrderDate;
        [Persistent(@"orderDate")]
        public DateTime OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref fOrderDate, value); }
        }
        DateTime fRequiredDate;
        [Persistent(@"requiredDate")]
        public DateTime RequiredDate
        {
            get { return fRequiredDate; }
            set { SetPropertyValue<DateTime>(nameof(RequiredDate), ref fRequiredDate, value); }
        }
        DateTime fShippedDate;
        [Persistent(@"shippedDate")]
        public DateTime ShippedDate
        {
            get { return fShippedDate; }
            set { SetPropertyValue<DateTime>(nameof(ShippedDate), ref fShippedDate, value); }
        }
        string fStatus;
        [Size(15)]
        [Persistent(@"status")]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        string fComments;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"comments")]
        public string Comments
        {
            get { return fComments; }
            set { SetPropertyValue<string>(nameof(Comments), ref fComments, value); }
        }
        Customers fCustomerNumber;
        [Persistent(@"customerNumber")]
        [Association(@"OrdersReferencesCustomers")]
        public Customers CustomerNumber
        {
            get { return fCustomerNumber; }
            set { SetPropertyValue<Customers>(nameof(CustomerNumber), ref fCustomerNumber, value); }
        }
    }

}
