//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace filtroDevExpress.classicmodels
{

    [Persistent(@"products")]
    public partial class Products : XPLiteObject
    {
        string fProductCode;
        [Key]
        [Size(15)]
        [Persistent(@"productCode")]
        public string ProductCode
        {
            get { return fProductCode; }
            set { SetPropertyValue<string>(nameof(ProductCode), ref fProductCode, value); }
        }
        string fProductName;
        [Size(70)]
        [Persistent(@"productName")]
        public string ProductName
        {
            get { return fProductName; }
            set { SetPropertyValue<string>(nameof(ProductName), ref fProductName, value); }
        }
        Productlines fProductLine;
        [Size(50)]
        [Persistent(@"productLine")]
        [Association(@"ProductsReferencesProductlines")]
        public Productlines ProductLine
        {
            get { return fProductLine; }
            set { SetPropertyValue<Productlines>(nameof(ProductLine), ref fProductLine, value); }
        }
        string fProductScale;
        [Size(10)]
        [Persistent(@"productScale")]
        public string ProductScale
        {
            get { return fProductScale; }
            set { SetPropertyValue<string>(nameof(ProductScale), ref fProductScale, value); }
        }
        string fProductVendor;
        [Size(50)]
        [Persistent(@"productVendor")]
        public string ProductVendor
        {
            get { return fProductVendor; }
            set { SetPropertyValue<string>(nameof(ProductVendor), ref fProductVendor, value); }
        }
        string fProductDescription;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"productDescription")]
        public string ProductDescription
        {
            get { return fProductDescription; }
            set { SetPropertyValue<string>(nameof(ProductDescription), ref fProductDescription, value); }
        }
        short fQuantityInStock;
        [Persistent(@"quantityInStock")]
        public short QuantityInStock
        {
            get { return fQuantityInStock; }
            set { SetPropertyValue<short>(nameof(QuantityInStock), ref fQuantityInStock, value); }
        }
        decimal fBuyPrice;
        [Persistent(@"buyPrice")]
        public decimal BuyPrice
        {
            get { return fBuyPrice; }
            set { SetPropertyValue<decimal>(nameof(BuyPrice), ref fBuyPrice, value); }
        }
        decimal fMSRP;
        public decimal MSRP
        {
            get { return fMSRP; }
            set { SetPropertyValue<decimal>(nameof(MSRP), ref fMSRP, value); }
        }
    }

}
